version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-tests
    ports:
     - "8080:8080"
    depends_on:
     - mongodb
  mongodb:
      image: mongo:4.1.10
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      ports:
          - 27017:27017
      command: mongod --logpath=/dev/null # --quiet