FROM golang:1.12.4
RUN mkdir -p /go/src/github.com/brunovale91/payment-api 
ADD . /go/src/github.com/brunovale91/payment-api/
WORKDIR /go/src/github.com/brunovale91/payment-api 
CMD ["go", "test", "-timeout", "30s", "-v", "github.com/brunovale91/payment-api"]